import 'package:flutter/material.dart';
import '../models/models.dart';
import '../state/app_state.dart';
import '../widgets/common.dart';

class DriverHome extends StatefulWidget{final AppState state;const DriverHome({super.key,required this.state});@override State<DriverHome>createState()=>_DriverHomeState();}
class _DriverHomeState extends State<DriverHome>{bool online=false;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Ngamia Driver 🐪'),actions:[IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const DriverProfile())),icon:const Icon(Icons.person))]),body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:SwitchListTile(value:online,onChanged:(v)=>setState(()=>online=v),title:Text(online?'Uko ONLINE':'Uko OFFLINE',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text(online?'Unaweza kupokea safari':'Washa ili upokee safari'),secondary:Icon(online?Icons.radio_button_checked:Icons.radio_button_off))),const MapCard(label:'Driver GPS'),const SizedBox(height:14),Row(children:[_stat('Leo',money(32500)),_stat('Trips','7'),_stat('Rating','4.9 ⭐')]),const SizedBox(height:12),if(online)Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.local_taxi)),title:const Text('Safari mpya'),subtitle:const Text('Pickup: Manzese Darajani\nDestination: Posta'),trailing:FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>DriverTrip(state:widget.state))),child:const Text('Fungua')))),Card(child:ListTile(leading:const Icon(Icons.account_balance_wallet_outlined),title:const Text('Mapato'),trailing:Text(money(widget.state.service.driverBalance)),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Earnings(state:widget.state))))),const Card(child:ListTile(leading:Icon(Icons.support_agent),title:Text('Help & Support'))]));Widget _stat(String a,String b)=>Expanded(child:Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[Text(a,style:const TextStyle(color:Colors.black54)),const SizedBox(height:5),Text(b,style:const TextStyle(fontWeight:FontWeight.bold))]))));}

class DriverTrip extends StatelessWidget{final AppState state;const DriverTrip({super.key,required this.state});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Safari mpya')),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[const MapCard(label:'Navigation'),const ListTile(title:Text('Pickup'),subtitle:Text('Manzese Darajani')),const ListTile(title:Text('Destination'),subtitle:Text('Posta')),const ListTile(title:Text('Estimated fare'),subtitle:Text('TZS 8,500')),const Spacer(),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>Navigator.pop(c),child:const Text('Kataa'))),const SizedBox(width:10),Expanded(child:FilledButton(onPressed:()=>showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('Safari imekubaliwa'),content:const Text('Mteja amepewa taarifa. Navigation ya production itaunganishwa na GPS.'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Sawa'))])),child:const Text('Kubali')))])]));}
class Earnings extends StatelessWidget{final AppState state;const Earnings({super.key,required this.state});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Mapato')),body:ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(title:const Text('Balance'),trailing:Text(money(state.service.driverBalance),style:const TextStyle(fontWeight:FontWeight.bold)))),const Card(child:ListTile(title:Text('Mapato ya leo'),trailing:Text('TZS 32,500'))),const Card(child:ListTile(title:Text('Commission ya Ngamia'),trailing:Text('20%'))),const SizedBox(height:10),FilledButton(onPressed:()=>showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('Withdrawal'),content:const Text('Production itaunganisha NMB, M-Pesa, Airtel Money na Tigo Pesa.'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Sawa'))])),child:const Text('Omba Withdrawal'))]));}
class DriverProfile extends StatelessWidget{const DriverProfile({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Driver Profile')),body:ListView(children:[const SizedBox(height:24),const CircleAvatar(radius:45,child:Icon(Icons.person,size:45)),const Center(child:Text('Juma Driver',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold))),const ListTile(leading:Icon(Icons.directions_car),title:Text('Toyota Premio'),subtitle:Text('T 123 ABC')),const ListTile(leading:Icon(Icons.badge),title:Text('Verification'),subtitle:Text('Pending production KYC')),const ListTile(leading:Icon(Icons.account_balance),title:Text('Payout account'))]));}
