import 'package:flutter/material.dart';
import '../models/models.dart';
import '../state/app_state.dart';
import '../widgets/common.dart';

class PassengerHome extends StatefulWidget { final AppState state; const PassengerHome({super.key,required this.state}); @override State<PassengerHome> createState()=>_PassengerHomeState(); }
class _PassengerHomeState extends State<PassengerHome>{
  final pickup=TextEditingController(text:'Manzese Darajani'); final dest=TextEditingController(); String vehicle='Ngamia Go'; int tab=0;
  int get fare=>vehicle=='Ngamia Go'?4500:vehicle=='Ngamia Comfort'?7000:10000;
  Future<void> book() async { if(dest.text.trim().isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Weka sehemu unayoenda.')));return;} final r=await widget.state.requestRide(pickup.text,dest.text,vehicle,fare); if(!mounted)return; if(r!=null)Navigator.push(context,MaterialPageRoute(builder:(_)=>RidePage(state:widget.state,ride:r))); }
  @override Widget build(BuildContext c){ if(tab==1)return HistoryPage(state:widget.state,onBack:()=>setState(()=>tab=0)); if(tab==2)return ProfilePage(state:widget.state,onBack:()=>setState(()=>tab=0)); return Scaffold(appBar:AppBar(title:const Text('Ngamia 🐪',style:TextStyle(fontWeight:FontWeight.bold)),actions:[IconButton(onPressed:()=>setState(()=>tab=2),icon:const Icon(Icons.account_circle_outlined))]),body:ListView(padding:const EdgeInsets.all(16),children:[
    const MapCard(),const SizedBox(height:16), _field(Icons.my_location,'Unatoka wapi?',pickup),const SizedBox(height:10),_field(Icons.location_on,'Unaenda wapi?',dest),const SizedBox(height:18),const SectionTitle('Chagua gari'),
    ...['Ngamia Go','Ngamia Comfort','Ngamia XL'].map((v)=>Card(child:RadioListTile<String>(value:v,groupValue:vehicle,onChanged:(x)=>setState(()=>vehicle=x!),title:Text(v),subtitle:Text(v=='Ngamia Go'?'Gari la kawaida':v=='Ngamia Comfort'?'Comfort zaidi':'Kikundi / mizigo'),secondary:Text(money(v=='Ngamia Go'?4500:v=='Ngamia Comfort'?7000:10000))))),
    Card(child:ListTile(leading:const Icon(Icons.payments_outlined),title:const Text('Malipo'),subtitle:const Text('Cash • Mobile Money itaongezwa'),trailing:const Icon(Icons.chevron_right))),const SizedBox(height:10),
    SizedBox(width:double.infinity,child:FilledButton(onPressed:widget.state.loading?null:book,style:FilledButton.styleFrom(padding:const EdgeInsets.symmetric(vertical:16)),child:widget.state.loading?const CircularProgressIndicator():Text('Omba Safari • ${money(fare)}'))),const SizedBox(height:8),
    OutlinedButton.icon(onPressed:()=>showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('SOS / Usalama'),content:const Text('Production itaunganisha emergency contact, live trip sharing na Safety Team.'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Funga'))])),icon:const Icon(Icons.shield_outlined),label:const Text('SOS / Usalama')),
  ]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Nyumbani'),NavigationDestination(icon:Icon(Icons.history),label:'Safari'),NavigationDestination(icon:Icon(Icons.person_outline),label:'Profile')]),); }
  Widget _field(IconData i,String h,TextEditingController x)=>TextField(controller:x,decoration:InputDecoration(prefixIcon:Icon(i),hintText:h,filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide.none)));
}

class RidePage extends StatelessWidget{final AppState state;final Ride ride;const RidePage({super.key,required this.state,required this.ride});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Safari yako')),body:ListView(padding:const EdgeInsets.all(16),children:[const MapCard(label:'Live tracking'),const SizedBox(height:16),Card(child:ListTile(leading:CircleAvatar(child:Icon(Icons.local_taxi)),title:Text('Dereva: ${ride.driver?.name??'Anatafutwa'}'),subtitle:Text('${ride.driver?.car??''} • ${ride.driver?.plate??''}\n⭐ ${ride.driver?.rating??0}'),trailing:IconButton(onPressed:()=>showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('Mawasiliano'),content:Text('Piga simu: ${ride.driver?.phone??''}'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Funga'))])),icon:const Icon(Icons.call)))),Card(child:ListTile(title:const Text('Safari'),subtitle:Text('${ride.pickup} → ${ride.destination}'),trailing:Text(money(ride.fare)))),const SizedBox(height:8),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:(){},icon:const Icon(Icons.chat),label:const Text('Chat'))),const SizedBox(width:8),Expanded(child:OutlinedButton.icon(onPressed:(){},icon:const Icon(Icons.share),label:const Text('Shiriki')))]),const SizedBox(height:8),FilledButton(onPressed:(){state.cancel(ride);Navigator.pop(c);},child:const Text('Ghairi safari'))]));}

class HistoryPage extends StatelessWidget{final AppState state;final VoidCallback onBack;const HistoryPage({super.key,required this.state,required this.onBack});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Safari zangu'),leading:IconButton(onPressed:onBack,icon:const Icon(Icons.arrow_back))),body:state.rides.isEmpty?const Center(child:Text('Bado hujaomba safari.')):ListView.builder(itemCount:state.rides.length,itemBuilder:(_,i){final r=state.rides[i];return Card(margin:const EdgeInsets.symmetric(horizontal:16,vertical:6),child:ListTile(leading:const CircleAvatar(child:Icon(Icons.local_taxi)),title:Text('${r.pickup} → ${r.destination}'),subtitle:Text(r.status.name),trailing:Text(money(r.fare)));}));}

class ProfilePage extends StatelessWidget{final AppState state;final VoidCallback onBack;const ProfilePage({super.key,required this.state,required this.onBack});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Profile'),leading:IconButton(onPressed:onBack,icon:const Icon(Icons.arrow_back))),body:ListView(children:[const SizedBox(height:20),const CircleAvatar(radius:44,child:Icon(Icons.person,size:45)),const SizedBox(height:8),Center(child:Text(state.user?.name??'Mtumiaji',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))),const SizedBox(height:20),const ListTile(leading:Icon(Icons.payment),title:Text('Payment methods')),const ListTile(leading:Icon(Icons.notifications_none),title:Text('Notifications')),const ListTile(leading:Icon(Icons.settings_outlined),title:Text('Settings')),const ListTile(leading:Icon(Icons.help_outline),title:Text('Help & Support')),ListTile(leading:const Icon(Icons.logout),title:const Text('Logout'),onTap:(){state.logout();Navigator.pop(c);})]));}
